apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    grafana:
      enabled: false
    prometheus:
      service:
        type: ClusterIP
    alertmanager:
      service:
        type: ClusterIP
    crds:
      enabled: true
    prometheusOperator:
      enabled: true
      admissionWebhooks:
        enabled: true
