apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloakx
  namespace: keycloakx
spec:
  interval: 10m
  chart:
    spec:
      chart: keycloakx
      sourceRef:
        kind: HelmRepository
        name: codecentric-oci
        namespace: keycloakx
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
    auth:
      adminUser: admin
      existingSecret: keycloak-admin
      secretKeys:
        adminPasswordKey: admin-password
    service:
      type: ClusterIP
    extraEnvVars:
      - { name: KC_PROXY, value: "edge" }
      - { name: KC_HTTP_ENABLED, value: "true" }
