apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 10m
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: cloudpirates-oci
        namespace: keycloak
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    postgres:
      enabled: true
      auth:
        database: keycloak
        username: bn_keycloak
        password: "changeme-please"
    auth:
      adminUser: admin
      existingSecret: keycloak-admin
      secretKeys:
        adminPasswordKey: admin-password
    service:
      type: ClusterIP
    extraEnvVars:
      - { name: KC_PROXY, value: "edge" }
      - { name: KC_HTTP_ENABLED, value: "true" }
