apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 10m
  chart:
    spec:
      chart: keycloak
      version: ">=25.0.0 <26.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    auth:
      adminUser: admin
      existingSecret: keycloak-admin
      passwordSecretKey: admin-password
    service:
      type: ClusterIP
