apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
  values:
    ui:
      enabled: true
    server:
      extraConfig: |
        telemetry {
          prometheus_retention_time = "24h"
          disable_hostname = true
          unauthenticated_metrics_access = true
        }
      serviceMonitor:
      enabled: true
      path: /v1/sys/metrics
      queryParameters:
        format: prometheus
      interval: 30s
      scrapeTimeout: 10s
      dev:
        enabled: true
        devRootToken: "root"
    injector:
      enabled: false
    csi:
      enabled: false
