apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repo.yaml
  - externalsecret-grafana.yaml
  - helmrelease-grafana.yaml
  - dashboards/keycloak-dashboard.yaml
  - dashboards/grafana-self-dashboard.yaml
  - dashboards/vault-dashboard.yaml
